### ISSUE TITLE
How can I make PrettyTabBar translucent?

### ISSUE THREAD

**Issue by mureev** [vicpenap/PrettyKit#13]
I can't make PrettyTabBar translucent. Even using iOS 5 appearance method witch works with UITabBar.

**Comment by vicpenap** [comment]
Can you add a screenshot with a translucent UITabBar, using iOS 5 as you say?

**Comment by mureev** [comment]
[[UITabBar appearance] setTintColor:[[UIColor alloc] initWithRed:0 green:0 blue:0 alpha:0.2]];
http://dl.dropbox.com/u/3481620/Screenshot_3.png

**Comment by vicpenap** [comment]
Thanks. PrettyTabBar can't be translucent right now. @echoz and I are currently working on some nice improvements on PrettyTabBar. You can join us to add this translucency feature. Take a look at the tabbar branch: https://github.com/vicpenap/PrettyKit/tree/tabbar and also to the issue #12.

**Comment by mureev** [comment]
Thanks.
