### ISSUE TITLE
Just Confused

### ISSUE THREAD

**Issue by Willio58** [vicpenap/PrettyKit#14]
I wanted to send this in a private message, but couldn't find how.. anyway, I'm just confused on this one thing. (and please bear with me because I'm rather new to coding)

In my app I have a tab bar and three views. I can implement the PrettyNavigationBar using interface builder in two out of the three views. The tableview is the one I am having trouble with. Is there a way i can implement a Prettynavbar inside a tableview using interface builder? -- I just can't figure out how..

**Comment by vicpenap** [comment]
I guess your setting up your third view as a table view. What you have to do is set it up as a navigation controller, and then, set the navigation controller's view as a table view. 

I'm closing the issue as it's not related with the library.
