### ISSUE TITLE
Separator shadow issue in grouped table

### ISSUE THREAD

**Issue by soulbuzz** [vicpenap/PrettyKit#15]
If you observe closely the place where the separator is drawn the shadow is broken. This happens even if the separator is not drawn. I am assuming this is some kind of margin between cells being drawn and its shadow path

**Comment by vicpenap** [comment]
Yeah, I'm aware of that. I haven't found the way to solve it yet, so
ideas about that are welcome.

**Comment by soulbuzz** [comment]
what is causing it ?. I have not looked into the code

**Comment by vicpenap** [comment]
In PrettyTableViewCell.m this is method that drops the shadow: `drawBorder:shadow:`

**Comment by vicpenap** [comment]
Issue was fixed in the commit mentioned above.
