### ISSUE TITLE
Access contentView of PrettyGridTableViewCell

### ISSUE THREAD

**Issue by Aniruddh-J** [vicpenap/PrettyKit#16]
This must be a dumb question but how can I access contentView of PrettyGridTableViewCell?

**Comment by vicpenap** [comment]
Well, you shouldn't, in fact. `PrettyCustomViewTableViewCell` has its content added inside a custom view, and this one directly inside the cell, not the cell's content view. That's done to avoid contentView's resizing when entering on different table view modes, such as editing mode, and to mask the content to the cell's shape.

And as `PrettyGridTableViewCell` inherits it, all the above applies to it too.

Anyway, if you need to access to it, use the `customView` property, inherited from `PrettyCustomViewTableViewCell`.

**Comment by Aniruddh-J** [comment]
Thanks for your reply, actually I have 4 elements in the cell and I want to add 4 different UIImageView in those PrettyCustomViewTableViewCell elements.

**Comment by vicpenap** [comment]
Well, grid cells draw with CoreGraphics all the content, so there's
just one UIView. It doesn't support images for the moment, although it
may do it in the future. So the only alternative right now is to
implement that without grid cells.

Or, forking the project, adding images support and making me a pull request :)
