### ISSUE TITLE
It doesn't work at searchDisplayController.searchResultsTableView 

### ISSUE THREAD

**Issue by mmmaru777** [vicpenap/PrettyKit#21]
PrettyKit is very nice library, but It doesn't work at searchDisplayController.searchResultsTableView.

```
static NSString *CellIdentifier = @"Cell";
PrettyTableViewCell *ccell = (PrettyTableViewCell *)[self.searchDisplayController.searchResultsTableView dequeueReusableCellWithIdentifier:CellIdentifier];
if (ccell == nil) {
  ccell = [[[PrettyTableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier] autorelease];
  ccell.tableViewBackgroundColor = self.searchDisplayController.searchResultsTableView.backgroundColor; 
  ccell.textLabel.font = [UIFont fontWithName:@"Palatino-Roman" size:14];
}

[ccell prepareForTableView:self.searchDisplayController.searchResultsTableView indexPath:indexPath];
ccell.textLabel.text = @"test";   
if (indexPath.section == 0) {
  ccell.cornerRadius = 20;
}
else {
  ccell.cornerRadius = 10;
}
```

Any ideas?  Thanks for your help.

**Comment by vicpenap** [comment]
What's the problem exactly?

**Comment by mmmaru777** [comment]
I use PrettyTableViewCell at searchDisplayController.searchResultsTableView, but the appearance of cell remains unchanged.

**Comment by vicpenap** [comment]
I guess that's because you're trying to set corner radius to a plain
tableview. Corner radius only applies to grouped tableviews.

**Comment by mmmaru777** [comment]
In my TableViewController.xib, I confirmed table view style was Grouped. The setting of my TableViewController.xib  is the same as PrettyExample/ExampleViewController.xib.

**Comment by vicpenap** [comment]
Yeah, but, as far as I know, a search tableview is always plain.

**Comment by mmmaru777** [comment]
Thanks for your help. 
I set searchResultsTableVewStyle to Grouped as below, then PrettyTableViewCell works! 
[self.searchDisplayController setValue:[NSNumber numberWithInt:UITableViewStyleGrouped]
                                  forKey:@"_searchResultsTableViewStyle"];

**Comment by vicpenap** [comment]
Good to know :)
