### ISSUE TITLE
PrettyGridTableViewCell duplicate member _indexPath

### ISSUE THREAD

**Issue by justinamberson** [vicpenap/PrettyKit#22]
Just a heads up, I'm not sure if this is a bug in XCode or what, but the newest NDAd XCode (DP3) is generating an error on line 99 that NSIndexPath *_indexPath; is a duplicate member, probably all the way back to UITableViewCell itself. Most likely a private property. I had to edit the .h and .m files and turned it into _indexPat, seems to have fixed it.

You'll have to keep watch for the next couple of preview releases to see if this continues

**Comment by vicpenap** [comment]
Hey thanks!

Yeah, it seems to be a duplicated ivar name, which hides an internal ivar. I will rename it in the next release to avoid any conflict.

Thanks!

**Comment by vicpenap** [comment]
Fixed with commit 442ae07
