### ISSUE TITLE
Default height of grouped style UITableViewCell should match SDK height

### ISSUE THREAD

**Issue by stevemoser** [vicpenap/PrettyKit#26]
The default height of a grouped PrettyKitTableViewCell is 44 while I believe the default height in the SDK is 50.

**Comment by vicpenap** [comment]
As far as I know it's 44 px in both plain and grouped styles.

**Comment by stevemoser** [comment]
Ah you are right. I remember there was a difference but it looks like it is only a pixel if it is the top or bottom cell.
http://stackoverflow.com/questions/594852/what-is-the-default-height-of-uitableviewcell

Yet my PrettyTableViewCells look better when the height is 50, does PrettyKit change the default font size?

**Comment by vicpenap** [comment]
Nope. But make sure you're calling the `neededHeight` method, that may
be the problem.

**Comment by stevemoser** [comment]
Thank you! Looks much better after calling neededHeightForIndexPath. Thats what I get for not reading the header file.

**Comment by vicpenap** [comment]
You're welcome :). There is some documentation, following the apple
style, available online at http://vicpenap.github.com/PrettyKit. Way
better than reading the .h :)

**Comment by stevemoser** [comment]
Nice. Though I might change the top part of the PrettyTableViewCell doc to mention that neededHeight should be implemented, probably next to the part about prepareForTableView:tableView needing to be implemented. Thanks again.

**Comment by vicpenap** [comment]
Yeah, that's true. Thanks :)
