### ISSUE TITLE
Add shadow to the PrettyToolBar

### ISSUE THREAD

**Issue by eyalc82** [vicpenap/PrettyKit#27]
Is there a way to add shadow to the PrettyToolBar?

**Comment by vicpenap** [comment]
Not yet :(

**Comment by eyalc82** [comment]
OK it can be a nice addition, thanks anyway great work

**Comment by vicpenap** [comment]
Yeah, maybe in the next release, we'll see :)

**Comment by vicpenap** [comment]
Available since commit 0d1de6b84, included in version 0.2.0

**Comment by eyalc82** [comment]
That was fast! thanks :)
