### ISSUE TITLE
How do I set the PrettyNavigationBar using a Navigation Controller in storyboard?

### ISSUE THREAD

**Issue by ghost** [vicpenap/PrettyKit#28]
I need to know how to set the PrettyNavigationBar using a Navigation Controller in storyboard?
Im dead stuck and i neeeed help!

**Comment by vicpenap** [comment]
Sorry, I haven't used Storyboards yet, so I can't help you with that.

**Comment by sridvijay** [comment]
You have to hide the navigation bar in your navigation controller and add a navigation bar to each of the view controllers that you want the navigation bar to be in, then just change the class to PrettyNavigationBar!

**Comment by ghost** [comment]
This would work, except I cant add navigation bars in storyboard to UITableViews. Any ideas? I tried to add one programatically, but the bar covers up the first cell.

**Comment by sridvijay** [comment]
That's weird, it works for me..? I just drag a navigation bar to the top of the view and it puts it right above the UITableView. However, if I have a UITableViewController, the navigation bar goes below my custom UITableViewCell, but when I run the app, it comes back on top.

**Comment by ghost** [comment]
Haha im such an idiot, I was dragging it to the wrong place!

**Comment by sridvijay** [comment]
Haha dont worry, we all have our moments :p!
