### ISSUE TITLE
UIStoryboard Cells

### ISSUE THREAD

**Issue by holtwick** [vicpenap/PrettyKit#3]
Hi, looks like your awesome toolkit does not work out of the box with UIStoryboard created cells (and I doubt it will work with NIBs anyway because of missing awakeFromNIB). Therefore I wrote a little workaround that seems to fix the problem:

```
- (void)configureCell {
    if(_configured) {
        return;
    }
    _configured = YES;

    [self.contentView addObserver:self forKeyPath:@"frame" options:NSKeyValueObservingOptionOld context:nil];


    PrettyTableViewCellBackground *bg = [[PrettyTableViewCellBackground alloc] initWithFrame:self.frame 
                                                                                    behavior:CellBackgroundBehaviorNormal];
    bg.cell = self;
    self.backgroundView = bg;
    [bg release];

    bg = [[PrettyTableViewCellBackground alloc] initWithFrame:self.frame
                                                     behavior:CellBackgroundBehaviorSelected];
    bg.cell = self;
    self.selectedBackgroundView = bg;
    [bg release];

    [self initializeVars];
}

- (id)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier
{
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    if (self) {
        [self configureCell];        
    }
    return self;
}
```

I added the call here too:

```
- (void) prepareForTableView:(UITableView *)tableView indexPath:(NSIndexPath *)indexPath 
{
    [self configureCell];
    _tableViewStyle = tableView.style;
    self.position = [PrettyTableViewCell positionForTableView:tableView indexPath:indexPath];
}
```

Hope this is somehow usefull.

Cheers, 
Dirk

**Comment by vicpenap** [comment]
Hi!

Thanks for your contribution! Why don't you make a pull request with your changes? That would be great. 

Cheers!

**Comment by holtwick** [comment]
Sorry, was just a quick hack... therefore I did not clone.

Another issue I found was that while reordering the borders of table cells are not updated, but I have no fix for it by now.

If I fiind and fix more I'll do it by pull requests, promissed ;)

**Comment by vicpenap** [comment]
Ha ha thanks :)

Yeah, about reordering, you'll have to tableView reloadRowsAtIndexPath for each pair of moved cells :)

**Comment by sarperdag** [comment]
Hey guys,

I used this method to solve problems that occur when working with custom cell xibs. However, the custom selection gradient colors still do not work. Any ideas?

```
    cell.selectionGradientStartColor = [UIColor colorWithHex:0xDD0000];;
    cell.selectionGradientEndColor = [UIColor colorWithHex:0xAA0000];;
```

**Comment by vicpenap** [comment]
Covered in #25
