### ISSUE TITLE
Animation and the backgroundView. Ugly stretching

### ISSUE THREAD

**Issue by Amnell** [vicpenap/PrettyKit#30]
Hi

I'm having trouble getting animations to work with PrettyKit cells.

I want to animate the cells height when a user taps the cell.

When a user selects the cell i call

```
[tableView beginUpdates];
[tableView endUpdates];
```

And returns a different height in `tableView:heightForRowAtIndexPath`. This makes the cell animate to its new height.

All this works like a charm, but I'm having trouble with the resizing of the backgroundView. Currently the backgroundViews content stretches while the cell animates. This is not what i want and it looks horrible. I want the backgroundView to redraw its content during the animation. Is this possible, and if so, how?

I've illustrated the problem in the following image (don't mind the arrow in the cell, its my custom implementation. Same behaviour with unmodified PrettyKit cells).

![Illustration](http://i.imgur.com/UopR8.png).

**Update:**
I found out that this is what happens:
1. The cell starts out as a big cell. Everything looks good and everyone is happy.
2. The user clicks the cell.
3. The backgroundView redraws for its new height.
4. The cell animates and gets smaller. And therefore the background view is in a stretched state during the animation.

**Comment by vicpenap** [comment]
Probably if you set the `contentMode` property to  `UIViewContentModeRedraw` that would work. 

Could you try that? If that works and you could make me a pull request, that would be a great favor :)

**Comment by Amnell** [comment]
I've set `contentMode` of `backgroundView` to  `UIViewContentModeRedraw` but without success. I've tried everything i can think of and now I'm running out of ideas :)

I've created a fork at https://github.com/apping/PrettyKit and in the branch `speech_bubble` the cell animates if you select it. Good for testing the issue.

Thanks

**Comment by vicpenap** [comment]
I've tried your example, but the cell never changes the height.

**Comment by Amnell** [comment]
My bad, didn't call ´[super layoutSubviews]´ in PrettyTableViewCell.m. Sloppy commit.
Just pushed a new commit. The cell should now resize when touched. Try it out :)

**Comment by vicpenap** [comment]
Thanks.

the mandatory call to  `[super layoutViews]` is setting the `backgroundView.frame` property to the cell's new frame, **before** the animation. So the backgroundView is being animated with the new frame. That's why it happens.

How to solve that? No idea :)

But, as a solution, you could use [VPPDropDown](https://github.com/vicpenap/VPPDropDown) to insert/remove a cell when the user taps. Take a look at it, it might solve your needs :)
