### ISSUE TITLE
consider adding developers from these branches to this project to keep it alive. 

### ISSUE THREAD

**Issue by johndpope** [vicpenap/PrettyKit#49]
![Uploading Screen Shot 2015-10-26 at 12.18.03 PM.png…]()

**Comment by vicpenap** [comment]
Hi, John. Something went wrong when you posted that image.

**Comment by johndpope** [comment]
![screen shot 2015-10-26 at 9 21 27 pm](https://cloud.githubusercontent.com/assets/289994/10726566/921fb4c8-7c27-11e5-96be-5d5c2ff23d01.png)

consider this tremendous amount of wasted effort. (incubated by github's inherent bad practice to fork this project) 
Consider adding some key people to this project without even bothering with pull requests. 
As there hasn't been an updated in over 3 years - the worst that can happen is that this project won't die of code rot.

**Comment by vicpenap** [comment]
Ok, I see. Yes, I agree. I'll take a look to see how I can do that. If you want to help out in this, please drop me a line on a private message.

**Comment by vicpenap** [comment]
I don't even see the value myself of maintaining this project anymore. MRC code, styles are prior iOS 7, just to mention a few reasons to discard using it.

**Comment by johndpope** [comment]
I arrived at this repo from this post trying to solve the problem of grouped tableviews http://stackoverflow.com/questions/18095223/changing-corner-radius-of-uitableview-grouped-in-ios6

**Comment by johndpope** [comment]
@vicpenap  - thanks for your efforts here. I'm closing out old github tickets.
