### ISSUE TITLE
PrettyTableViewCell subtitle problem

### ISSUE THREAD

**Issue by zhouhesheng** [vicpenap/PrettyKit#6]
very pretty, thanks for the great job. 

I wish to display detailLabel in prettytableviewcell, but the background of the detaillabel text was cleared so the background of the tableview is displayed. How can I solve the problem? thank you.

**Comment by vicpenap** [comment]
I'm afraid I didn't understand you. What's exactly the problem?

**Comment by zhouhesheng** [comment]
this page includes the screen shot when i add subtitle into table view cell in PlainExample.m:

http://blog.sina.com.cn/s/blog_53eb9bc001012yy3.html

**Comment by Willio58** [comment]
I'm very new to coding but what i did to get around it was: 

 PrettyTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
    if (cell == nil) {
        cell = [[[PrettyTableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:CellIdentifier] autorelease];
        cell.tableViewBackgroundColor = tableView.backgroundColor;  
        cell.customBackgroundColor = start_color;                    <-------------I Added This
        cell.gradientStartColor = start_color;  
        cell.gradientEndColor = end_color;
    }

**Comment by zhouhesheng** [comment]
thanks, the solve my question.

**Comment by vicpenap** [comment]
OK, I understand. In that case, you can change the detailTextLabel backgroundColor. 

Something like this should do the trick:
`cell.detailTextLabel.backgroundColor = start_color;` 
or
`cell.detailTextLabel.backgroundColor = [UIColor clearColor];` 

First one would be better at performance, but it some cases it won't be pixel perfect. Second one: worse at performance, but pixel perfect :)
